"use client";
import { useRouter } from "next/navigation";
import { Minus, Package, Plus } from "lucide-react";
import { formatPriceDisplay } from "@/features/products/lib/format-price";
import type { StorefrontOffer, StorefrontProduct } from "@/features/storefront/hooks/use-public-store";
export function StorefrontProductCard({ slug, product, offer, qty, onAdd, onInc, onDec, orderingDisabled, previewMode }: { slug: string; product: StorefrontProduct; offer?: StorefrontOffer; qty: number; onAdd: () => void; onInc: () => void; onDec: () => void; orderingDisabled: boolean; previewMode?: boolean }) {
  const router = useRouter();
  return <div className="overflow-hidden rounded-xl border border-border bg-card text-left"><button type="button" onClick={() => router.push(`/store/${slug}/p/${product.id}`)} className="block w-full text-left"><div className="relative aspect-[3/2] overflow-hidden bg-muted">{product.image_url ? <img src={product.image_url} alt={product.name} loading="lazy" decoding="async" className="h-full w-full object-cover" /> : <div className="flex h-full w-full items-center justify-center"><Package className="h-8 w-8 text-muted-foreground/40" /></div>}{offer && <span className="absolute top-1.5 left-1.5 rounded-full bg-[#FEF3C7] px-1.5 py-0.5 text-[8px] leading-none font-bold text-[#D97706]">OFFER</span>}</div><div className="px-2 pt-2"><p className="mb-1 line-clamp-2 text-[11px] leading-snug font-semibold text-foreground">{product.name}</p>{offer ? <div className="mb-1.5"><div className="flex flex-wrap items-baseline gap-1"><span className="text-xs font-bold text-foreground">₹{formatPriceDisplay(offer.offerPrice)}</span>{offer.regularPrice != null && <span className="text-[9px] text-muted-foreground line-through">₹{formatPriceDisplay(offer.regularPrice)}</span>}</div>{offer.saving != null && offer.saving > 0 && <p className="text-[9px] font-semibold text-[#D97706]">Save ₹{formatPriceDisplay(offer.saving)}</p>}<p className="text-[9px] text-muted-foreground">per {product.unit || "piece"}</p></div> : product.price != null ? <div className="mb-1.5 flex items-baseline gap-1"><span className="text-xs font-bold text-foreground">₹{formatPriceDisplay(product.price)}</span><span className="text-[9px] text-muted-foreground">per {product.unit || "piece"}</span></div> : <p className="mb-1.5 text-[10px] text-muted-foreground">Price on request · per {product.unit || "piece"}</p>}</div></button><div className="px-2 pb-2.5">{orderingDisabled ? <div className="flex h-11 w-full items-center justify-center rounded-lg bg-muted"><span className="text-[10px] text-muted-foreground">{previewMode ? "Add" : "Closed"}</span></div> : qty > 0 ? <div className="flex h-11 w-full items-center justify-between rounded-lg bg-foreground"><button type="button" onClick={onDec} className="flex h-11 w-11 items-center justify-center"><Minus className="h-3 w-3 text-background" /></button><span className="text-xs font-semibold text-background">{qty} {product.unit}</span><button type="button" onClick={onInc} disabled={qty >= 99} className="flex h-11 w-11 items-center justify-center disabled:opacity-40"><Plus className="h-3 w-3 text-background" /></button></div> : <button type="button" onClick={onAdd} className="h-11 w-full rounded-lg bg-foreground text-[11px] font-semibold text-background">Add</button>}</div></div>;
}
