const MIN_QTY = 0.5;
const MAX_QTY = 99;
export interface CartStorage { getItem(key: string): string | null; setItem(key: string, value: string): void; removeItem(key: string): void; }
export interface CartItem { productId: string; name: string; unit: string; qty: number; hadOffer: boolean; }
const cache = new Map<string, CartItem[]>(); const listeners = new Map<string, Set<() => void>>();
export function cartStorageKey(slug: string): string { return `cart:${slug}`; }
function resolveStorage(storage: CartStorage | undefined): CartStorage | undefined { if (storage) return storage; if (typeof localStorage === "undefined") return undefined; return localStorage; }
function stepForUnit(unit: string): number { return unit === "kg" || unit === "litre" ? 0.5 : 1; }
function clampQty(value: number): number { if (!Number.isFinite(value)) return MIN_QTY; return Math.round(Math.min(MAX_QTY, Math.max(MIN_QTY, value)) * 2) / 2; }
function notify(slug: string): void { listeners.get(slug)?.forEach(listener => listener()); }
function sanitizeEntries(parsed: unknown): CartItem[] | null { if (!Array.isArray(parsed)) return null; const result: CartItem[] = []; for (const raw of parsed) { if (typeof raw !== "object" || raw === null) return null; const entry = raw as Record<string, unknown>; if (typeof entry.productId !== "string" || entry.productId.length === 0 || typeof entry.name !== "string" || typeof entry.unit !== "string" || typeof entry.qty !== "number" || !Number.isFinite(entry.qty)) return null; result.push({ productId: entry.productId, name: entry.name, unit: entry.unit, qty: clampQty(entry.qty), hadOffer: entry.hadOffer === true }); } return result; }
export function readCart(slug: string, storage?: CartStorage): readonly CartItem[] { const cached = cache.get(slug); if (cached) return cached; const store = resolveStorage(storage); let items: CartItem[] = []; if (store) { try { const raw = store.getItem(cartStorageKey(slug)); if (raw) items = sanitizeEntries(JSON.parse(raw)) ?? []; } catch { items = []; } } cache.set(slug, items); return items; }
export function writeCart(slug: string, items: CartItem[], storage?: CartStorage): void { cache.set(slug, items); const store = resolveStorage(storage); if (store) { try { if (items.length === 0) store.removeItem(cartStorageKey(slug)); else store.setItem(cartStorageKey(slug), JSON.stringify(items)); } catch {} } notify(slug); }
export function subscribeToCart(slug: string, listener: () => void): () => void { let set = listeners.get(slug); if (!set) { set = new Set(); listeners.set(slug, set); } set.add(listener); return () => set.delete(listener); }
export function addOrIncrementItem(items: readonly CartItem[], entry: { productId: string; name: string; unit: string; hadOffer: boolean }): CartItem[] { const existing = items.find(item => item.productId === entry.productId); const step = stepForUnit(entry.unit); if (existing) return items.map(item => item.productId === entry.productId ? { ...item, qty: clampQty(item.qty + step) } : item); return [...items, { productId: entry.productId, name: entry.name, unit: entry.unit, qty: step, hadOffer: entry.hadOffer }]; }
export function incrementItemQty(items: readonly CartItem[], productId: string): CartItem[] { return items.map(item => item.productId === productId ? { ...item, qty: clampQty(item.qty + stepForUnit(item.unit)) } : item); }
export function decrementItemQty(items: readonly CartItem[], productId: string): CartItem[] { const existing = items.find(item => item.productId === productId); if (!existing) return items as CartItem[]; const step = stepForUnit(existing.unit); if (existing.qty <= step) return items.filter(item => item.productId !== productId); return items.map(item => item.productId === productId ? { ...item, qty: clampQty(item.qty - step) } : item); }
export function removeCartItem(items: readonly CartItem[], productId: string): CartItem[] { return items.filter(item => item.productId !== productId); }
